name: Whee

on: [push]

jobs:
  first:
    runs-on: ubuntu-18.04
    name: this is my first job
    steps:
      - run: ls && pwd
      # - name: Install dependencies
      #   run: | 
      #     sudo apt-get -y update
      #     sudo apt-get -y upgrade
      #     sudo apt-get -y install python3-pip
      #     sudo python3 install.py
      #     sudo pip install -r requirements.txt
      # - name: Run tests
      #   run: |
      #     python3 omf/runAllTests.py
